# Content & Acknowledgements
This data was scraped from publicly available results posted every week from Domain.com.au, I've cleaned it as best I can, now it's up to you to make data analysis magic. The dataset includes Address, Type of Real estate, Suburb, Method of Selling, Rooms, Price, Real Estate Agent, Date of Sale and distance from C.B.D.

….Now with extra data including including property size, land size and council area, you may need to change your code!

## Some Key Details
Suburb: Suburb

Address: Address

Rooms: Number of rooms

Price: Price in Australian dollars

Method:
S - property sold;
SP - property sold prior;
PI - property passed in;
PN - sold prior not disclosed;
SN - sold not disclosed;
NB - no bid;
VB - vendor bid;
W - withdrawn prior to auction;
SA - sold after auction;
SS - sold after auction price not disclosed.
N/A - price or highest bid not available.

Type:
br - bedroom(s);
h - house,cottage,villa, semi,terrace;
u - unit, duplex;
t - townhouse;
dev site - development site;
o res - other residential.

SellerG: Real Estate Agent

Date: Date sold

Distance: Distance from CBD in Kilometres

Regionname: General Region (West, North West, North, North east …etc)

Propertycount: Number of properties that exist in the suburb.

Bedroom2 : Scraped # of Bedrooms (from different source)

Bathroom: Number of Bathrooms

Car: Number of carspots

Landsize: Land Size in Metres

BuildingArea: Building Size in Metres

YearBuilt: Year the house was built

CouncilArea: Governing council for the area

Lattitude: Self explanitory

Longtitude: Self explanitory

In [115]:
import pandas as pd

data = pd.read_csv ("Melbourne_housing_FULL.csv")

data.shape

(34857, 21)

In [116]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [117]:
data.head(15)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra City Council,-37.7969,144.9969,Northern Metropolitan,4019.0
6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra City Council,-37.8072,144.9941,Northern Metropolitan,4019.0
7,Abbotsford,16 Maugie St,4,h,NaN,SN,Nelson,6/08/2016,2.5,3067.0,...,2.0,2.0,400.0,220.0,2006.0,Yarra City Council,-37.7965,144.9965,Northern Metropolitan,4019.0
8,Abbotsford,53 Turner St,2,h,NaN,S,Biggin,6/08/2016,2.5,3067.0,...,1.0,2.0,201.0,NaN,1900.0,Yarra City Council,-37.7995,144.9974,Northern Metropolitan,4019.0
9,Abbotsford,99 Turner St,2,h,NaN,S,Collins,6/08/2016,2.5,3067.0,...,2.0,1.0,202.0,NaN,1900.0,Yarra City Council,-37.7996,144.9989,Northern Metropolitan,4019.0
10,Abbotsford,129 Charles St,2,h,941000.0,S,Jellis,7/05/2016,2.5,3067.0,...,1.0,0.0,181.0,NaN,NaN,Yarra City Council,-37.8041,144.9953,Northern Metropolitan,4019.0
11,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra City Council,-37.8024,144.9993,Northern Metropolitan,4019.0
12,Abbotsford,121/56 Nicholson St,2,u,NaN,PI,Biggin,7/11/2016,2.5,3067.0,...,2.0,1.0,4292.0,82.0,2009.0,Yarra City Council,-37.8078,144.9965,Northern Metropolitan,4019.0
13,Abbotsford,17 Raphael St,4,h,NaN,W,Biggin,7/11/2016,2.5,3067.0,...,2.0,0.0,230.0,147.0,1860.0,Yarra City Council,-37.8066,144.9936,Northern Metropolitan,4019.0
14,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,1.0,2.0,256.0,107.0,1890.0,Yarra City Council,-37.8060,144.9954,Northern Metropolitan,4019.0

In [118]:
unique_values = data.nunique()

print(unique_values)

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [119]:
# convert strg datetime objects
data["Date"] = pd.to_datetime(data["Date"], format="%d/%m/%Y", errors="coerce")

In [120]:
# count the null values
NullCounts = data.isnull().sum()

In [121]:
NullCounts

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [122]:
TopAgents = data["SellerG"].value_counts().head(15).index

data["Agents"] = data["SellerG"].where(data["SellerG"].isin(TopAgents), "others")

In [123]:
data = data.drop(columns=["SellerG"])

In [124]:
ColumnMapper = {
    "Bedroom2": "BedroomNo",
    "Lattitude": "Latitude",
    "Car": "CarNo",
    "Bathroom": "BathroomNo"
}
data = data.rename(columns=ColumnMapper)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   Date           34857 non-null  datetime64[ns]
 7   Distance       34856 non-null  float64
 8   Postcode       34856 non-null  float64
 9   BedroomNo      26640 non-null  float64
 10  BathroomNo     26631 non-null  float64
 11  CarNo          26129 non-null  float64
 12  Landsize       23047 non-null  float64
 13  BuildingArea   13742 non-null  float64
 14  YearBuilt      15551 non-null  float64
 15  CouncilArea    34854 non-null  object
 16  Latitude       26881 non-null  float64
 17  Longtitude     26881 non-null  float64
 18  Regionname     34854 non-null  object
 19  Propertycount  34854 non-null  float64
 20  Agents         34857 non-null  object
dtypes: datetime64[ns](1), float64(12), int64(1), object(7)
memory usage: 5.6+ MB

In [125]:
NumericValues = ["BathroomNo", "CarNo", "Landsize", "BuildingArea", "YearBuilt", "Distance", "Propertycount","Latitude", "Longtitude", "BedroomNo", "Price"]

In [136]:
CategoricalValues = ["CouncilArea", "Regionname", "Suburb", "Type", "Method", "Agents"]

In [137]:
# replace nulls
for feature in CategoricalValues:
    if feature in data.columns:
        data[feature] = data[feature].fillna("Unknown")

In [138]:
for value in NumericValues:
    if value in data.columns:
        valueMedian = data[value].median()
        data[value] = data[value].fillna(valueMedian)

In [139]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Rooms          34857 non-null  int64
 2   Type           34857 non-null  object
 3   Price          34857 non-null  float64
 4   Method         34857 non-null  object
 5   Distance       34857 non-null  float64
 6   Postcode       34856 non-null  float64
 7   BedroomNo      34857 non-null  float64
 8   BathroomNo     34857 non-null  float64
 9   CarNo          34857 non-null  float64
 10  Landsize       34857 non-null  float64
 11  BuildingArea   34857 non-null  float64
 12  YearBuilt      34857 non-null  float64
 13  CouncilArea    34857 non-null  object
 14  Latitude       34857 non-null  float64
 15  Longtitude     34857 non-null  float64
 16  Regionname     34857 non-null  object
 17  Propertycount  34857 non-null  int64
 18  Agents         34857 non-null  object
 19  SalesYear      34857 non-null  int32
 20  SalesMonth     34857 non-null  int32
dtypes: float64(11), int32(2), int64(2), object(6)
memory usage: 5.3+ MB

In [140]:
data["SalesYear"] = data["Date"].dt.year
data["SalesMonth"] = data["Date"].dt.month

data = data.drop(columns=["Date"])

KeyError: 'Date'

In [ ]:
data = data.drop(columns=["Address"])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Rooms          34857 non-null  int64
 2   Type           34857 non-null  object
 3   Price          34857 non-null  float64
 4   Method         34857 non-null  object
 5   Distance       34857 non-null  float64
 6   Postcode       34856 non-null  float64
 7   BedroomNo      34857 non-null  float64
 8   BathroomNo     34857 non-null  float64
 9   CarNo          34857 non-null  float64
 10  Landsize       34857 non-null  float64
 11  BuildingArea   34857 non-null  float64
 12  YearBuilt      34857 non-null  float64
 13  CouncilArea    34857 non-null  object
 14  Latitude       34857 non-null  float64
 15  Longtitude     34857 non-null  float64
 16  Regionname     34857 non-null  object
 17  Propertycount  34857 non-null  float64
 18  Agents         34857 non-null  object
 19  SalesYear      34857 non-null  int32
 20  SalesMonth     34857 non-null  int32
dtypes: float64(12), int32(2), int64(1), object(6)
memory usage: 5.3+ MB

In [ ]:
DiscreteValues = ["PostCode", "Bedroom2", "Bathroom", "Car", "Propertycount"]
for columns in DiscreteValues:
    if columns in data.columns:
        data[columns] = data[columns].astype(int)

In [142]:
data = pd.get_dummies(data, columns=CategoricalValues, drop_first=True)

In [143]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Columns: 431 entries, Rooms to Agents_others
dtypes: bool(416), float64(11), int32(2), int64(2)
memory usage: 17.6 MB

In [144]:
data.head(15)

,Rooms,Price,Distance,Postcode,BedroomNo,BathroomNo,CarNo,Landsize,BuildingArea,YearBuilt,...,Agents_Jellis,Agents_Marshall,Agents_McGrath,Agents_Nelson,Agents_Noel,Agents_RT,Agents_Ray,Agents_Woodards,Agents_hockingstuart,Agents_others
0,2,870000.0,2.5,3067.0,2.0,1.0,1.0,126.0,136.0,1970.0,...,True,False,False,False,False,False,False,False,False,False
1,2,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.0,136.0,1970.0,...,False,False,False,False,False,False,False,False,False,False
2,2,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,...,False,False,False,False,False,False,False,False,False,False
3,3,870000.0,2.5,3067.0,3.0,2.0,1.0,0.0,136.0,1970.0,...,False,False,False,False,False,False,False,False,False,True
4,3,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,...,False,False,False,False,False,False,False,False,False,False
5,3,850000.0,2.5,3067.0,3.0,2.0,1.0,94.0,136.0,1970.0,...,False,False,False,False,False,False,False,False,False,False
6,4,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,...,False,False,False,True,False,False,False,False,False,False
7,4,870000.0,2.5,3067.0,3.0,2.0,2.0,400.0,220.0,2006.0,...,False,False,False,True,False,False,False,False,False,False
8,2,870000.0,2.5,3067.0,4.0,1.0,2.0,201.0,136.0,1900.0,...,False,False,False,False,False,False,False,False,False,False
9,2,870000.0,2.5,3067.0,3.0,2.0,1.0,202.0,136.0,1900.0,...,False,False,False,False,False,False,False,False,False,True
10,2,941000.0,2.5,3067.0,2.0,1.0,0.0,181.0,136.0,1970.0,...,True,False,False,False,False,False,False,False,False,False
11,3,1876000.0,2.5,3067.0,4.0,2.0,0.0,245.0,210.0,1910.0,...,False,False,False,True,False,False,False,False,False,False
12,2,870000.0,2.5,3067.0,2.0,2.0,1.0,4292.0,82.0,2009.0,...,False,False,False,False,False,False,False,False,False,False
13,4,870000.0,2.5,3067.0,6.0,2.0,0.0,230.0,147.0,1860.0,...,False,False,False,False,False,False,False,False,False,False
14,2,1636000.0,2.5,3067.0,2.0,1.0,2.0,256.0,107.0,1890.0,...,False,False,False,True,False,False,False,False,False,False

In [145]:
data.to_csv("Melbourne_Cleaned_Encoded.csv", index=False)